name: audio-search
channels:
  - defaults
  - nvidia
  - pytorch
dependencies:
  - blas=1.0
  - brotlicffi=1.1.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - cuda-cccl=12.9.27
  - cuda-cccl_win-64=12.9.27
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-libraries-dev=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.9.19
  - cuda-opencl-dev=12.9.19
  - cuda-profiler-api=12.9.79
  - cuda-runtime=12.1.0
  - cuda-version=12.9
  - expat=2.7.3
  - filelock=3.20.0
  - freetype=2.13.3
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - idna=3.11
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - jpeg=9f
  - khronos-opencl-icd-loader=2025.07.22
  - lcms2=2.16
  - lerc=3.0
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcufft=11.0.2.4
  - libcufft-dev=11.0.2.4
  - libcurand=10.3.10.19
  - libcurand-dev=10.3.10.19
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libdeflate=1.17
  - libffi=3.4.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnpp-dev=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.105
  - libnvjpeg=12.1.1.14
  - libnvjpeg-dev=12.1.1.14
  - libpng=1.6.50
  - libtiff=4.5.1
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - networkx=3.4.2
  - numpy-base=2.0.1
  - opencl-headers=2025.07.22
  - openjpeg=2.5.2
  - openssl=3.0.18
  - pillow=11.1.0
  - pip=25.3
  - pycparser=2.23
  - pysocks=1.7.1
  - python=3.10.19
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.3
  - requests=2.32.5
  - setuptools=80.9.0
  - sqlite=3.51.0
  - sympy=1.14.0
  - tbb=2021.8.0
  - tk=8.6.15
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - annotated-types==0.7.0
      - anyio==4.11.0
      - attrs==25.4.0
      - audioread==3.1.0
      - backoff==2.2.1
      - bcrypt==5.0.0
      - build==1.3.0
      - cachetools==6.2.2
      - chromadb==1.3.5
      - click==8.3.1
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - decorator==5.2.1
      - distro==1.9.0
      - durationpy==0.10
      - exceptiongroup==1.3.1
      - flatbuffers==25.9.23
      - fsspec==2025.10.0
      - google-auth==2.43.0
      - googleapis-common-protos==1.72.0
      - grpcio==1.76.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kubernetes==34.1.0
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.45.1
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - mmh3==5.2.0
      - msgpack==1.1.2
      - mutagen==1.47.0
      - numba==0.62.1
      - numpy==2.2.6
      - oauthlib==3.3.1
      - onnxruntime==1.23.2
      - opentelemetry-api==1.38.0
      - opentelemetry-exporter-otlp-proto-common==1.38.0
      - opentelemetry-exporter-otlp-proto-grpc==1.38.0
      - opentelemetry-proto==1.38.0
      - opentelemetry-sdk==1.38.0
      - opentelemetry-semantic-conventions==0.59b0
      - orjson==3.11.4
      - overrides==7.7.0
      - packaging==25.0
      - platformdirs==4.5.0
      - pooch==1.8.2
      - posthog==5.4.0
      - protobuf==6.33.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybase64==1.4.2
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - pyqt6==6.10.0
      - pyqt6-qt6==6.10.1
      - pyqt6-sip==13.10.2
      - pyreadline3==3.5.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - referencing==0.37.0
      - regex==2025.11.3
      - requests-oauthlib==2.0.0
      - rich==14.2.0
      - rpds-py==0.29.0
      - rsa==4.9.1
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soxr==1.0.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - tomli==2.3.0
      - torch==2.9.1
      - torchaudio==2.9.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - transformers==4.57.3
      - typer==0.20.0
      - typing-inspection==0.4.2
      - urllib3==2.3.0
      - uvicorn==0.38.0
      - watchfiles==1.1.1
      - websocket-client==1.9.0
      - websockets==15.0.1
      - zipp==3.23.0
prefix: C:\Users\gdiaz\miniconda3\envs\audio-search
